server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
    
    
management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - beans
        - health
        - mappings