
# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port
  
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    keycloak:
        path: /auth/**
        stripPrefix: false
        sensitiveHeaders: true
        url: http://localhost:8089/
    account-service:
        path: /api/accounts/**
        stripPrefix: false
        sensitiveHeaders: false

    delivery-service:
        path: /delivery-service/**
        stripPrefix: true
 
    order-service:
        path: /order-service/**
        stripPrefix: true
        sensitiveHeaders: true

 