
# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port
  
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    authorization:
        path: /oauth/**
        stripPrefix: false
        sensitiveHeaders: true
    accounts-service:
        path: /api/accounts/**
        stripPrefix: false
        sensitiveHeaders: false

    delivery-service:
        path: /delivery-service/**
        stripPrefix: true
 
