Vagrant.configure("2") do |config|

  config.vm.define "host1" do |host|
    host.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
      v.name = "host1"
    end
    host.vm.box = "ubuntu/bionic64"
    host.vm.provision :shell, path: "addkey.sh"
    host.vm.network "private_network", ip: "192.168.99.3"
  end

  config.vm.define "host2" do |host|
    host.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
      v.name = "host2"
    end
    host.vm.box = "ubuntu/bionic64"
    host.vm.provision :shell, path: "addkey.sh"
    host.vm.network "private_network", ip: "192.168.99.2"
  end

  
end


